src/ElislamBundle/Entity/Blog.php
<?php

namespace ElislamBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Blog
 *
 * @ORM\Table(name="blog")
 * @ORM\Entity(repositoryClass="ElislamBundle\Repository\BlogRepository")
 */
class Blog
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="text", type="text")
     */
    private $text;

    /**
     * @var string
     * @Assert\NotBlank(message="please insert an image here.")
     * @Assert\Image()
     * @ORM\Column(name="images", type="string", length=255)
     */
    private $images;


    /**
     *
     *
     * @ORM\ManyToOne(targetEntity="ElislamBundle\Entity\BlogCat", inversedBy="categorie")
     * @ORM\JoinColumn(name="categorie_id", referencedColumnName="id")
     *
     */
    private $categorie_id;

    /**
     * @var \DateTime
     *
     *
     * @ORM\Column(name="datetime", type="datetime")
     */
    private $datetime;

    public function __construct()
    {
        $this->datetime = new \DateTime();
    }


    /**
     * @var string
     *
     * @ORM\Column(name="naam", type="string", length=255)
     */
    private $naam;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Blog
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set text
     *
     * @param string $text
     *
     * @return Blog
     */
    public function setText($text)
    {
        $this->text = $text;

        return $this;
    }

    /**
     * Get text
     *
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Set images
     *
     * @param string $images
     *
     * @return Blog
     */
    public function setImages($images)
    {
        $this->images = $images;

        return $this;
    }

    /**
     * Get images
     *
     * @return string
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * Set datetime
     *
     * @param \DateTime $datetime
     *
     * @return Blog
     */
    public function setDatetime($datetime)
    {
        $this->datetime = $datetime;

        return $this;
    }

    /**
     * Get datetime
     *
     * @return \DateTime
     */
    public function getDatetime()
    {
        return $this->datetime;
    }

    /**
     * Set naam
     *
     * @param string $naam
     *
     * @return Blog
     */
    public function setNaam($naam)
    {
        $this->naam = $naam;

        return $this;
    }

    /**
     * Get naam
     *
     * @return string
     */
    public function getNaam()
    {
        return $this->naam;
    }
    /**
     * @return string
     */
    /**
     * @return mixed
     */
    public function getCategorieId()
    {
        return $this->categorie_id;
    }

    /**
     * @param mixed $categorie_id
     */
    public function setCategorieId($categorie_id)
    {
        $this->categorie_id = $categorie_id;
    }
}

src/ElislamBundle/Form/BlogType.php
<?php

namespace ElislamBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class BlogType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title')
                ->add('text')
                ->add('images',FileType::class,array('label'=>'insert image'))
                ->add('categorie_id')
                ->add('datetime')
                ->add('naam');

    }/**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ElislamBundle\Entity\Blog'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'elislambundle_blog';
    }


}

src/ElislamBundle/Controller/BlogController.php
<?php

namespace ElislamBundle\Controller;

use ElislamBundle\Entity\Blog;
use ElislamBundle\Form\BlogType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Filesystem\Filesystem;

/**
 * Blog controller.
 *
 * @Route("blog")
 */
class BlogController extends Controller
{
    /**
     * Lists all blog entities.
     *
     * @Route("/", name="blog_index")
     * @Method("GET")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $blogs = $em->getRepository('ElislamBundle:Blog')->findAll();

        return $this->render('@Elislam/blog/index.html.twig', array(
            'blogs' => $blogs,
        ));
    }

    /**
     * Creates a new blog entity.
     * @Route("/blog/new", name="blog_new")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Method({"GET", "POST"})
     */
    public function newAction(Request $request)
    {
        $blog = new Blog();


        $form = $this->createForm(BlogType::class, $blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Generate a unique name for the file before saving it
            $file = $blog->getImages();
            $fileName = md5(uniqid()).'.'.$file->guessExtension();

            $file->move(
                $this->getParameter('image_directory'),$fileName
            );

            $blog->setImages($fileName);
            $em = $this->getDoctrine()->getManager();
            $em->persist($blog);
            $em->flush();


            return $this->redirectToRoute('blog_show', array('id' => $blog->getId()));
        }

        return $this->render('@Elislam/blog/new.html.twig', array(
            'blog' => $blog,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a blog entity.
     *
     * @Route("/{id}", name="blog_show")
     * @Method("GET")
     */
    public function showAction(Blog $blog)
    {
        $deleteForm = $this->createDeleteForm($blog);

        $blog = $this->getDoctrine()
            ->getRepository(Blog::class)
            ->find($blog);
        return $this->render('@Elislam/blog/show.html.twig', array(
            'blog' => $blog,
            'delete_form' => $deleteForm->createView(),
        ));



    }

    /**
     * Displays a form to edit an existing blog entity.
     *
     * @Route("/{id}/edit", name="blog_edit")
     * @Method({"GET", "POST"})
     */
    public function editAction(Request $request, Blog $blog)
    {
        $deleteForm = $this->createDeleteForm($blog);
        $editForm = $this->createForm('ElislamBundle\Form\BlogType', $blog);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $blog->setImages(
                new File($blog->getImages())
            );
            // $file stores the uploaded image
            /*
            * @var Symfony\Component\HttpFoundation\File\UploadedFile $file
            */
            $file = $blog->getImages();

            /*            if ($file) {
                            unlink($file);
                        }*/
            // Generate a unique name for the file before saving it
            $fileName = md5(uniqid()) . '.' . $file->guessExtension();

            $file->move(
                $this->getParameter('image_directory'), $fileName
            );

            $blog->setImages($fileName);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('blog_edit', array('id' => $blog->getId()));
        }

        return $this->render('@Elislam/blog/edit.html.twig', array(
            'blog' => $blog,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a blog entity.
     *
     * @Route("/{id}", name="blog_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, Blog $blog)
    {
        $form = $this->createDeleteForm($blog);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($blog);
            $em->flush();
        }

        return $this->redirectToRoute('blog_index');
    }

    /**
     * Creates a form to delete a blog entity.
     *
     * @param Blog $blog The blog entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Blog $blog)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('blog_delete', array('id' => $blog->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
}

src/ElislamBundle/Resources/views/blog/edit.html.twig
{% extends '@Elislam/Default/base.html.twig' %}

{% block body %}
    <h1>Blog edit</h1>

    {{ form_start(edit_form) }}
        {{ form_widget(edit_form) }}
        <input type="submit" value="Edit" />
    {{ form_end(edit_form) }}

    <ul>
        <li>
            <a href="{{ path('blog_index') }}">Back to the list</a>
        </li>
        <li>
            {{ form_start(delete_form) }}
                <input type="submit" value="Delete">
            {{ form_end(delete_form) }}
        </li>
    </ul>
{% endblock %}

src/ElislamBundle/Resources/views/blog/index.html.twig
{% extends '@Elislam/Default/base.html.twig' %}
{% block stylesheets %}
    <link href="{{ asset('bundles/elislam/css/sub.css') }}" rel="stylesheet">
{% endblock %}
{% block body %}
    {% if app.user %}
        <div class="container-fluid col-11">
            <h1 class="text-center text-white">Blog lijst</h1>
            <table class="table table-striped table-dark table-bordered table-responsive">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Text</th>
                    <th>Images</th>
                    <th>Categorie</th>
                    <th>Datetime</th>
                    <th>Writer</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for blog in blogs %}
                    <tr>
                        <td>{{ blog.id }}</td>
                        <td>{{ blog.title }}</td>
                        <td>{{ blog.text }}</td>
                        <td>{{ blog.images }}</td>
                        <td>{{ blog.categorieId }}</td>
                        <td>{% if blog.datetime %}{{ blog.datetime|date('Y-m-d H:i:s') }}{% endif %}</td>
                        <td>{{ blog.naam }}</td>
                        <td>
                            <a href="{{ path('blog_show', { 'id': blog.id }) }}" style="padding-right: 7px; float: left"><span class="fa fa-eye"></span></a>
                            <a href="{{ path('blog_edit', { 'id': blog.id }) }}"><span class="fa fa-edit"></span></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <button class="btn btn-success space_box"><a href="{{ path('blog_new') }}"><span class="fa fa-plus" style="color: #FFFFFF;"> Create a new media</span></a></button>
        </div>
    {% else %}
        <-- yilmaz deze mag aangepast worden. -->
        <div class="container-fluid">

            <div class="row">

                <!-- Blog Entries Column -->
                <div class="col-md-8">

                    <h1 class="my-4 text-center font-weight-bold text-info">Blogs
                    </h1>
                    {% for blog in blogs %}
                        <!-- Blog Post -->
                        <div class="card mb-4">
                            <div class="card-body">
                                <div class="col-md-3">
                                    <img class="card-img-top" src="{{ asset('uploads/images/' ~ blog.images) }}" alt="Card image cap">
                                </div>
                                <div class="col-md-2">
                                    <h2 class="card-title">{{ blog.title }}</h2>
                                    <p class="card-text">{{ blog.text }}</p>
                                    <a href="#" class="btn btn-primary">Read More &rarr;</a>
                                </div>
                                </div>
                            <div class="card-footer text-muted">
                                Posted on {{ blog.datetime |date('d-m-Y H:i') }} by
                                <a href="#">{{ blog.naam }}</a>
                            </div>
                        </div>
                    {% endfor %}
                    <!-- Pagination -->
                    <ul class="pagination justify-content-center mb-4">
                        <li class="page-item">
                            <a class="page-link" href="#">&larr; Older</a>
                        </li>
                        <li class="page-item disabled">
                            <a class="page-link" href="#">Newer &rarr;</a>
                        </li>
                    </ul>

                </div>

                <!-- Sidebar Widgets Column -->
                <div class="col-md-4">

                    <!-- Search Widget -->
                    <div class="card my-4">
                        <h5 class="card-header">Search</h5>
                        <div class="card-body">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search for...">
                                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
                            </div>
                        </div>
                    </div>

                    <!-- Categories Widget -->
                    <div class="card my-4">
                        <h5 class="card-header">Categories</h5>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <a href="">blog-Page</a>
                                        </li>
                                        <li>
                                            <a href="#">Event-Page</a>
                                        </li>
                                        <li>
                                            <a href="#">Lezing-Page</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="col-lg-6">
                                    <ul class="list-unstyled mb-0">
                                        <li>
                                            <a href="#">Vrijdag-Page</a>
                                        </li>
                                        <li>
                                            <a href="#">Theologie-Page</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container -->
    {% endif %}
{% endblock %}

src/ElislamBundle/Resources/views/blog/new.html.twig
{% extends '@Elislam/Default/base.html.twig' %}

{% block body %}

    <h1 class="text-center">maak een blog</h1>

    {{ form_start(form) }}

        {{ form_widget(form) }}
        <input class="btn btn-lg btn-outline-primary" type="submit" value="Create" style="margin-bottom: 10px;"/>
    {{ form_end(form) }}

    <button class="btn btn-success space_box float-left btn-space"><a href="{{ path('blog_index') }}"><span class="fa fa-chevron-circle-left" style="color: #FFFFFF;"> back to list</span></a></button>
{% endblock %}

src/ElislamBundle/Resources/views/blog/show.html.twig
{% extends '@Elislam/Default/base.html.twig' %}
{% block stylesheets %}
    <link href="{{ asset('bundles/elislam/css/sub.css') }}" rel="stylesheet">
{% endblock %}
{% block body %}
    <div class="container-fluid col-9">
        <h1 class="text-center text-white">Blog </h1>
        <table class="table table-striped table-dark table-bordered table-responsive">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ blog.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ blog.title }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ blog.text }}</td>
            </tr>
            <tr>
                <th>Images</th>
                <td>{{ blog.images }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ blog.categorieId }}</td>
            </tr>
            <tr>
                <th>Datetime</th>
                <td>{% if blog.datetime %}{{ blog.datetime|date('Y-m-d H:i:s') }}{% endif %}</td>
            </tr>
            <tr>
                <th>Naam</th>
                <td>{{ blog.naam }}</td>
            </tr>
            </tbody>
        </table>
        <button class="btn btn-success space_box float-left btn-space"><a href="{{ path('blog_index') }}"><span class="fa fa-chevron-circle-left" style="color: #FFFFFF;"> back to list</span></a></button>
        <button class="btn btn-success space_box float-left btn-space"><a href="{{ path('blog_edit', { 'id': blog.id }) }}"><span class="fa fa-edit" style="color: #FFFFFF;">edit blog</span></a></button>
        {{ form_start(delete_form) }}
        <button class="btn btn-success space_box" type="submit"><span class="fa fa-trash" style="color: #FFFFFF;"> Delete</span></button>
        {{ form_end(delete_form) }}
    </div>
{% endblock %}